---@alias tab_size {rows: integer, cols: integer, pixel_width: integer, pixel_height: integer, dpi: integer}
---@alias workspace_state {workspace: string, window_states: window_state[]}
---@alias window_state {title: string, tabs: tab_state[], workspace: string, size: tab_size}
---@alias tab_state {title: string, pane_tree: pane_tree, is_active: boolean, is_zoomed: boolean}
---@alias session_state {format_version: integer, generation: integer?, saved_at: integer?, active_workspace: string, active_window: integer?, windows: window_state[]}
---@alias MuxTab any
---@alias MuxWindow any

---Restore options. Panes are only ever created through `spawn_pane`; no saved process, argv or text is executed.
---`on_warning(message)` is called at most once per outermost restore with the summarized, non-fatal problems (for example missing folders).
---@alias restore_opts {spawn_in_workspace: boolean?, workspace_name: string?, close_open_tabs: boolean?, close_open_panes: boolean?, pane: Pane?, tab: MuxTab?, window: MuxWindow?, spawn_pane: (fun(leaf: pane_leaf, opts: table): (table, string?))?, on_pane_restore: (fun(leaf: pane_leaf))?, on_warning: (fun(message: string))?}
